;;;; cadre.asd — Cadre, a Lisp editor

(defsystem "cadre"
  :description "Cadre: a Common Lisp editor with Emacs's depth and VS Code's interface."
  :author "Jessie Hughart"
  :license "MIT"
  :version "0.0.1"
  :depends-on ("cadre/core" "gtk4" "gtk4-adwaita")
  :pathname "src/ui/"
  :serial t
  :components ((:file "package")
               (:file "gtk-text")
               (:file "settings")
               (:file "themes")
               (:file "keys")
               (:file "highlight")
               (:file "editor-view")
               (:file "explorer")
               (:file "panel")
               (:file "window")
               (:file "tabs")
               (:file "tab-strip")
               (:file "layout")
               (:file "commands")
               (:file "picker")
               (:file "search")
               (:file "lisp-commands")
               (:file "editing")
               (:file "paredit")
               (:file "macros")
               (:file "session")
               (:file "repl")
               (:file "notes")
               (:file "debugger")
               (:file "completion")
               (:file "lisp-eval")
               (:file "hints")
               (:file "image-faces")
               (:file "inspector")
               (:file "presentations")
               (:file "xref")
               (:file "macroexpand")
               (:file "trace")
               (:file "stepper")
               (:file "systems")
               (:file "review")
               (:file "file-watch")
               (:file "claude-tools")
               (:file "claude")
               (:file "editor-repl")
               (:file "restore")
               (:file "settings-page")
               (:file "project-search")
               (:file "refactor")
               (:file "markdown")
               (:file "file-ops")
               (:file "outline")
               (:file "everyday")
               (:file "git")
               (:file "git-history")
               (:file "git-merge")
               (:file "folding")
               (:file "tree-sitter")
               (:file "format")
               (:file "new-project")
               (:file "build")
               (:file "gtk-app")
               (:file "bindings")
               (:file "app"))
  :in-order-to ((test-op (test-op "cadre/tests"))))

(defsystem "cadre/core"
  :description "Cadre's editor model, with no GTK dependency: text, buffers, commands, keymaps, modes, hooks, options."
  :depends-on ("sb-bsd-sockets" "sb-posix" "sb-introspect" "cl-ppcre" "cffi")
  :pathname "src/core/"
  :serial t
  :components ((:file "package")
               (:file "hooks")
               (:file "options")
               (:file "text")
               (:file "keymaps")
               (:file "modes")
               (:file "buffers")
               (:file "editor")
               (:file "commands")
               (:file "editing")
               (:file "fuzzy")
               (:module "lisp"
                :serial t
                :components ((:file "lexer")
                             (:file "syntax")
                             (:file "indent")
                             (:file "faces")
                             (:file "paredit")
                             (:file "refactor")))
               (:file "search")
               (:file "definitions" :pathname "lisp/definitions")
               (:file "markdown")
               (:file "folding")
               (:file "format")
               (:file "git")
               (:file "new-project")
               (:module "swank"
                :serial t
                :components ((:file "sexp")
                             (:file "connection")
                             (:file "inferior")
                             (:file "forms")
                             (:file "tools")
                             (:file "image")))
               (:file "build")
               (:file "tree-sitter" :pathname "tree-sitter/tree-sitter")
               (:module "claude"
                :serial t
                :components ((:file "json")
                             (:file "cli")
                             (:file "mcp")
                             (:file "diff")))))

(defsystem "cadre/tests"
  :description "Headless tests for cadre/core."
  :depends-on ("cadre/core" "parachute")
  :pathname "tests/"
  :serial t
  :components ((:file "package")
               (:file "text")
               (:file "buffers")
               (:file "commands")
               (:file "keymaps")
               (:file "lisp")
               (:file "editing")
               (:file "swank")
               (:file "claude"))
  :perform (test-op (op c) (uiop:symbol-call :parachute :test :cadre-tests)))
