(in-package #:cadre-tests)

;;; M4: JSON, the CLI's stream-json, the MCP server, diffs

(define-test json :parent cadre-tests
  (let ((v (c:parse-json "{\"a\": [1, 2.5, -3e2, true, false, null], \"b\": {\"c\": \"x\\ny\\u00e9\\ud83d\\ude00\"}, \"d\": []}")))
    (is equalp #(1 2.5d0 -300.0d0 t :false :null) (c:jget v "a"))
    (is string= (format nil "x~%yé~a" (code-char #x1F600)) (c:jget v "b" "c"))
    (is = 2.5d0 (c:jget v "a" 1))
    (is eq nil (c:jget v "missing" "deeper"))
    (is equalp #() (c:jget v "d")))
  (is string= "{\"k\":\"a\\\"b\\n\",\"n\":[1,true,false,null],\"o\":{}}"
      (c:json-string (c:jobj "k" (format nil "a\"b~%") "n" (vector 1 t :false nil) "o" (c:jobj) "skip" :omit)))
  (let ((round (c:parse-json (c:json-string (c:jobj "x" (vector (c:jobj "y" "é")))))))
    (is string= "é" (c:jget round "x" 0 "y")))
  (fail (c:parse-json "{\"a\": }") 'c:json-error)
  (fail (c:parse-json "[1, 2") 'c:json-error)
  (fail (c:parse-json "1 2") 'c:json-error))

(define-test claude-events :parent cadre-tests
  (let ((e (first (c:parse-claude-event "{\"type\":\"system\",\"subtype\":\"init\",\"session_id\":\"s1\",\"model\":\"claude-sonnet\",\"mcp_servers\":[{\"name\":\"cadre\",\"status\":\"connected\"}]}"))))
    (is eq :init (c:event-kind e))
    (is string= "s1" (c:event-session-id e))
    (is equal '(("cadre" . "connected")) (c:event-data e)))
  (let ((e (first (c:parse-claude-event "{\"type\":\"stream_event\",\"event\":{\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":\"Hel\"}},\"parent_tool_use_id\":null}"))))
    (is eq :text-delta (c:event-kind e))
    (is string= "Hel" (c:event-text e))
    (false (c:event-subagent e)))
  (let ((events (c:parse-claude-event "{\"type\":\"assistant\",\"message\":{\"content\":[{\"type\":\"text\",\"text\":\"Hi\"},{\"type\":\"tool_use\",\"id\":\"t1\",\"name\":\"mcp__cadre__read_buffer\",\"input\":{\"buffer\":\"a.lisp\"}}]}}")))
    (is equal '(:text :tool-use) (mapcar #'c:event-kind events))
    (is string= "a.lisp" (c:jget (c:event-input (second events)) "buffer"))
    (is string= "read_buffer" (c:tool-display-name (c:event-name (second events)))))
  (let ((e (first (c:parse-claude-event "{\"type\":\"user\",\"message\":{\"content\":[{\"type\":\"tool_result\",\"tool_use_id\":\"t1\",\"content\":[{\"type\":\"text\",\"text\":\"ok\"}],\"is_error\":true}]}}"))))
    (is eq :tool-result (c:event-kind e))
    (is string= "ok" (c:event-text e))
    (true (c:event-error e)))
  (let ((e (first (c:parse-claude-event "{\"type\":\"result\",\"subtype\":\"success\",\"is_error\":false,\"result\":\"Done\",\"total_cost_usd\":0.0123,\"duration_ms\":900,\"session_id\":\"s1\"}"))))
    (is eq :result (c:event-kind e))
    (false (c:event-error e))
    (is = 0.0123d0 (c:event-cost e)))
  (is eq nil (c:parse-claude-event "not json"))
  (let ((line (c:parse-json (c:user-message-line "fix it"))))
    (is string= "user" (c:jget line "type"))
    (is string= "fix it" (c:jget line "message" "content" 0 "text")))
  (let ((args (c:claude-arguments :session-id "u" :model "sonnet" :allowed-tools '("Read" "Grep")
                                  :disallowed-tools '("Edit") :permission-tool "mcp__cadre__approve")))
    (true (search '("--session-id" "u") args :test #'equal))
    (true (search '("--allowedTools" "Read,Grep") args :test #'equal))
    (true (search '("--permission-prompt-tool" "mcp__cadre__approve") args :test #'equal)))
  (true (search '("--resume" "u") (c:claude-arguments :resume "u" :session-id "v") :test #'equal))
  (is = 36 (length (c:make-uuid)))
  (is char= #\4 (char (c:make-uuid) 14)))

(c:define-mcp-tool "test_echo" (args)
  "Echo the text."
  (("text" "string" "What to echo" :required t))
  (format nil "echo: ~a" (c:tool-argument args "text" :required t)))

(define-test mcp-server :parent cadre-tests
  (let* ((server (c:start-mcp-server))
         (url (c:mcp-server-url server))
         (token (c:mcp-server-token server)))
    (unwind-protect
         (progn
           (multiple-value-bind (status reply)
               (c:http-post-json url token (c:jobj "jsonrpc" "2.0" "id" 1 "method" "initialize"
                                                   "params" (c:jobj "protocolVersion" "2025-03-26")))
             (is = 200 status)
             (is string= "2025-03-26" (c:jget reply "result" "protocolVersion"))
             (is string= "cadre" (c:jget reply "result" "serverInfo" "name")))
           (is = 202 (c:http-post-json url token (c:jobj "jsonrpc" "2.0" "method" "notifications/initialized")))
           (multiple-value-bind (status reply)
               (c:http-post-json url token (c:jobj "jsonrpc" "2.0" "id" 2 "method" "tools/list"))
             (is = 200 status)
             (let ((tool (find "test_echo" (c:jget reply "result" "tools") :key (lambda (x) (c:jget x "name")) :test #'equal)))
               (true tool)
               (is equalp #("text") (c:jget tool "inputSchema" "required"))))
           (multiple-value-bind (status reply)
               (c:http-post-json url token (c:jobj "jsonrpc" "2.0" "id" 3 "method" "tools/call"
                                                   "params" (c:jobj "name" "test_echo" "arguments" (c:jobj "text" "hé"))))
             (is = 200 status)
             (is string= "echo: hé" (c:jget reply "result" "content" 0 "text"))
             (is eq :false (c:jget reply "result" "isError")))
           (let ((reply (nth-value 1 (c:http-post-json url token (c:jobj "jsonrpc" "2.0" "id" 4 "method" "tools/call"
                                                                         "params" (c:jobj "name" "test_echo" "arguments" (c:jobj)))))))
             (is eq t (c:jget reply "result" "isError"))
             (true (search "Missing argument" (c:jget reply "result" "content" 0 "text"))))
           (is = 401 (c:http-post-json url "wrong" (c:jobj "jsonrpc" "2.0" "id" 5 "method" "ping")))
           (let* ((dir (merge-pathnames (format nil "cadre-mcp-test-~d/" (random 100000)) (uiop:temporary-directory)))
                  (path (c:write-mcp-config server dir)))
             (unwind-protect
                  (let ((config (c:parse-json (uiop:read-file-string path))))
                    (is string= url (c:jget config "mcpServers" "cadre" "url"))
                    (is = #o600 (logand #o777 (sb-posix:stat-mode (sb-posix:stat (namestring path))))))
               (uiop:delete-directory-tree dir :validate t))))
      (c:stop-mcp-server server))))

(define-test diffs :parent cadre-tests
  (is equal '((:same "a") (:removed "b") (:added "B") (:same "c"))
      (c:diff-lines '("a" "b" "c") '("a" "B" "c")))
  (is equal '((:same "a") (:added "x") (:same "b"))
      (c:diff-lines '("a" "b") '("a" "x" "b")))
  (is equal '((:removed "a"))
      (c:diff-lines '("a") '()))
  (is equal '("a" "b") (c:split-lines (format nil "a~%b~%")))
  (is string= "one TWO three" (c:replace-unique "one two three" "two" "TWO"))
  (fail (c:replace-unique "a a" "a" "b") 'c:mcp-tool-error)
  (fail (c:replace-unique "abc" "x" "y") 'c:mcp-tool-error))
