(in-package #:cadre-tests)

;;; Paredit. Texts mark the cursor with |.

(defun text-with-cursor (string)
  (let* ((point (position #\| string))
         (text (c:make-string-text (remove #\| string :count 1))))
    (setf (c:text-point text) point)
    text))

(defun shown-with-cursor (text)
  (let ((s (c:text-string text)) (p (c:text-point text)))
    (concatenate 'string (subseq s 0 p) "|" (subseq s p))))

(defun paredit (function string &rest args)
  "STRING after FUNCTION, with the cursor shown as |."
  (let* ((text (text-with-cursor string))
         (syntax (c:make-lisp-syntax text)))
    (multiple-value-bind (line column) (c:text-position-line text (c:text-point text))
      (multiple-value-bind (edits point stick delta) (apply function syntax line column args)
        (c:apply-edits text edits point (or stick :before) (or delta 0))
        (shown-with-cursor text)))))

(define-test paredit :parent cadre-tests
  (is string= "(a b| c)" (paredit #'c:paredit-slurp-forward "(a b|) c"))
  (is string= "(a (b| c d))" (paredit #'c:paredit-slurp-forward "(a (b| c) d)"))
  (is string= "(a b|) c" (paredit #'c:paredit-barf-forward "(a b| c)"))
  (is string= "(|)a" (paredit #'c:paredit-barf-forward "(|a)"))
  (is string= "(a b| c)" (paredit #'c:paredit-slurp-backward "a (b| c)"))
  (is string= "a (b| c)" (paredit #'c:paredit-barf-backward "(a b| c)"))
  (is string= "(let ((x 1)) |(foo x))" (paredit #'c:paredit-raise "(let ((x 1)) (when t |(foo x)))"))
  (is string= "(f |x)" (paredit #'c:paredit-raise "(f (g |x y))"))
  (is string= "(a b| c d)" (paredit #'c:paredit-splice "(a (b| c) d)"))
  (is string= "(a |c d)" (paredit #'c:paredit-splice-killing-backward "(a (b |c d))"))
  (is string= "(a b|)" (paredit #'c:paredit-splice-killing-forward "(a (b| c d))"))
  (is string= "((|(a b)) c)" (paredit #'c:paredit-wrap "(|(a b) c)"))
  (is string= "(f (|x))" (paredit #'c:paredit-wrap "(f |x)"))
  (is string= "(|)" (paredit #'c:paredit-wrap "|"))
  (is string= "(a b)| (c)" (paredit #'c:paredit-split "(a b| c)"))
  (is string= "\"ab\"| \"cd\"" (paredit #'c:paredit-split "\"ab|cd\""))
  (is string= "(a b |c d)" (paredit #'c:paredit-join "(a b) |(c d)"))
  (fail (paredit #'c:paredit-slurp-forward "(a b|)"))
  (fail (paredit #'c:paredit-raise "|a"))
  ;; Typing
  (is string= "(f (|))" (paredit #'c:paredit-open "(f |)"))
  (is string= "\"(|\"" (paredit #'c:paredit-open "\"|\""))
  (is string= "#\\(|" (paredit #'c:paredit-open "#\\|"))
  (is string= "(a (b c)|)" (paredit #'c:paredit-close "(a (b c|  ))"))
  (is string= "(a (b c)|)" (paredit #'c:paredit-close "(a (b c|))"))
  (is string= "(f \"|\")" (paredit #'c:paredit-quote "(f |)"))
  (is string= "\"ab\"|" (paredit #'c:paredit-quote "\"ab|\""))
  (is string= "\"a\\\"|b\"" (paredit #'c:paredit-quote "\"a|b\""))
  ;; Deleting
  (is string= "(a (|))" (paredit #'c:paredit-delete-before "(a ()|)"))
  (is string= "(a |)" (paredit #'c:paredit-delete-before "(a (|))"))
  (is string= "(a (b)|)" (paredit #'c:paredit-delete-before "(a (b))|"))
  (is string= "(a |(b))" (paredit #'c:paredit-delete-before "(a (|b))"))
  (is string= "(a |)" (paredit #'c:paredit-delete-before "(a \"|\")"))
  (is string= "(a \"x|\")" (paredit #'c:paredit-delete-before "(a \"x\"|)"))
  (is string= "(ab|)" (paredit #'c:paredit-delete-before "(abc|)"))
  (is string= "(a |)" (paredit #'c:paredit-delete-after "(a |())"))
  (is string= "(a (|b))" (paredit #'c:paredit-delete-after "(a |(b))"))
  (is string= "(a b)|" (paredit #'c:paredit-delete-after "(a b|)"))
  (is string= "\"a|\"" (paredit #'c:paredit-delete-after "\"a|\\n\""))
  ;; How far C-k kills
  (flet ((kill-end (string)
           (let* ((text (text-with-cursor string))
                  (syntax (c:make-lisp-syntax text)))
             (multiple-value-bind (line column) (c:text-position-line text (c:text-point text))
               (let ((end (c:paredit-kill-end syntax line column)))
                 (concatenate 'string (c:text-string text 0 (c:text-point text)) (c:text-string text end)))))))
    (is string= "(a )" (kill-end "(a |b c)"))
    (is string= "(defun f ()
  
   (bar))" (kill-end "(defun f ()
  |(foo)
   (bar))"))
    (is string= "x ; c
y" (kill-end "x|(a
 b) ; c
y"))
    (is string= "(f \"ab\")" (kill-end "(f \"ab|cd\")"))
    (is string= "ab" (kill-end "a|
b"))))

;;; The kill ring

(define-test kill-ring :parent cadre-tests
  (let ((c:*kill-ring* '()) (c::*kill-ring-yank-index* 0) (c:*last-command-kind* nil) (c:*this-command-kind* nil))
    (fail (c:current-kill))
    (c:kill-text "one")
    (is string= "one" (c:current-kill))
    ;; A second kill right after joins the first.
    (setf c:*last-command-kind* :kill)
    (c:kill-text " two")
    (c:kill-text "zero " :direction :backward)
    (is equal '("zero one two") c:*kill-ring*)
    (setf c:*last-command-kind* nil)
    (c:kill-text "three")
    (c:kill-new "four")
    (is string= "four" (c:current-kill))
    (is string= "three" (c:current-kill 1))
    (is string= "zero one two" (c:current-kill 1))
    (is string= "four" (c:current-kill 1))
    (let ((c:*kill-ring-max* 2))
      (c:kill-new "five")
      (is = 2 (length c:*kill-ring*)))))

(define-test replacing :parent cadre-tests
  (is equal '((0 . 3) (8 . 11)) (c:find-all "foo" "Foo bar foo"))
  (is equal '((8 . 11)) (c:find-all "foo" "Foo bar foo" :case-fold nil))
  (is equal '((4 . 7)) (c:find-all "Bar" "foo Bar bar"))
  (is string= "bar" (c:replacement-for "foo" "bar"))
  (is string= "Bar" (c:replacement-for "Foo" "bar"))
  (is string= "BAR" (c:replacement-for "FOO" "bar"))
  (is string= "bAr" (c:replacement-for "FOO" "bAr"))
  (is equal '("Bar baz BAR" 2) (multiple-value-list (c:replace-all "foo" "bar" "Foo baz FOO")))
  (is string= "Hello" (c:capitalize-string "hELLO"))
  (is equal '("defun" "define-command") (c:dabbrev-candidates "def" "(defun x) (def| y) (define-command z) (defun w)" 14))
  (is equal '("make-buffer") (c:dabbrev-candidates "make-" "(make-buffer) make-" 19)))

(define-test minor-modes :parent cadre-tests
  (c:define-minor-mode test-minor-mode ())
  (let ((buffer (c:make-buffer :name "minor")))
    (unwind-protect
         (progn
           (false (c:minor-mode-enabled-p buffer 'test-minor-mode))
           (c:set-minor-mode buffer 'test-minor-mode t)
           (true (c:minor-mode-enabled-p buffer 'test-minor-mode))
           (is = 1 (length (c:buffer-minor-mode-keymaps buffer)))
           (c:set-minor-mode buffer 'test-minor-mode nil)
           (false (c:minor-mode-enabled-p buffer 'test-minor-mode)))
      (c:kill-buffer buffer))))

(define-test prefix-argument :parent cadre-tests
  (let ((count 0))
    (eval `(c:define-command test-repeated () (:repeat t) (incf ,(intern "*TEST-COUNT*" :cadre-tests))))
    (defparameter *test-count* 0)
    (let ((c:*prefix-arg* 3)) (c:run-command 'test-repeated))
    (is = 3 *test-count*)
    (let ((c:*prefix-arg* '(4))) (c:run-command 'test-repeated))
    (is = 7 *test-count*)
    (is = 1 (c:prefix-numeric-value nil))
    (setf count 0)
    count))

;;; Options, as the settings page edits them

(defvar *test-flag* nil)
(defvar *test-count* 3)
(defvar *test-choice* :a)
(defvar *test-name* nil)
(defvar *test-list* '("a"))

(define-test options :parent cadre-tests
  (c:define-option *test-flag* nil boolean "A flag." :category "Testing")
  (c:define-option *test-count* 3 (integer 1 10) "A count.")
  (c:define-option *test-choice* :a (member :a :b) "A choice.")
  (c:define-option *test-name* nil (or null string) "A name.")
  (c:define-option *test-list* '("a") list "A list.")
  (flet ((o (name) (c:find-option name)))
    (is string= "Testing" (c:option-category (o '*test-flag*)))
    (is string= "Other" (c:option-category (o '*test-count*)))
    (is string= "Test count" (c:option-title (o '*test-count*)))
    (is eq :boolean (c:option-kind (o '*test-flag*)))
    (is equal '(:integer 1 10) (c:option-kind (o '*test-count*)))
    (is equal '(:choice (:a :b)) (c:option-kind (o '*test-choice*)))
    (is eq :optional-string (c:option-kind (o '*test-name*)))
    (is eq :lisp (c:option-kind (o '*test-list*)))
    (is equal '("x" "y") (c:read-option-value (o '*test-list*) "(\"x\" \"y\")"))
    (is eq nil (c:read-option-value (o '*test-name*) "  "))
    (is string= "Ann" (c:read-option-value (o '*test-name*) "Ann"))
    (is = 7 (c:read-option-value (o '*test-count*) "7"))
    (fail (c:read-option-value (o '*test-count*) "70"))
    (fail (c:read-option-value (o '*test-list*) "(oops"))
    (fail (c:read-option-value (o '*test-list*) "#.(error \"no\")"))
    (fail (c:set-option-value (o '*test-choice*) :c))
    (c:set-option-value (o '*test-choice*) :b)
    (is eq :b *test-choice*)
    (is string= "(\"a\")" (c:write-option-value (o '*test-list*)))
    (is string= "" (c:write-option-value (o '*test-name*)))))

;;; Searching and refactoring

(define-test project-search :parent cadre-tests
  (is equal '((0 4 7) (1 0 3)) (c:text-matches (format nil "the foo~%Foo-bar") "foo"))
  (is equal '((0 4 7)) (c:text-matches (format nil "the foo~%Foo-bar") "foo" :whole-word t))
  (is equal '((1 0 3)) (c:text-matches (format nil "the foo~%Foo-bar") "Foo" :case-sensitive t))
  (is equal '((0 7 10) (1 10 13))
      (c:symbol-occurrences (format nil "(defun foo () \"foo\") ; foo~%(cl-user::foo 1 foo-bar)") "foo"))
  (is equal '((0 1 4)) (c:symbol-occurrences "(Bar)" "pkg:bar"))
  (is string= (format nil "(defun baz () \"foo\")~%(baz)")
      (c:replace-matches (format nil "(defun foo () \"foo\")~%(foo)")
                         (c:symbol-occurrences (format nil "(defun foo () \"foo\")~%(foo)") "foo") "baz")))

(defun after-edits (text edits)
  (let ((st (c:make-string-text text)))
    (c:apply-edits st edits 0)
    (c:text-string st)))

(define-test refactoring :parent cadre-tests
  (let ((tree (c:read-form-tree "(a (b c) ; x
 \"s\")")))
    (is = 1 (length tree))
    (is = 3 (length (fourth (first tree)))))
  (let ((text "(defun f (x &key (y 2)) (let ((z 3)) (+ x y z w)))"))
    (let ((start (search "(+ x" text)))
      (is equal '("x" "y" "z") (sort (c:bound-variables-at (c:read-form-tree text) start (+ start 11)) #'string<))))
  (let* ((text "(defun area (w h)
  (let ((pad 2))
    (* (+ w pad) h)))")
         (start (search "(+ w pad)" text)))
    (multiple-value-bind (edits params) (c:extract-function-edits text start (+ start 9) "padded")
      (is equal '("w" "pad") params)
      (is string= "(defun padded (w pad)
  (+ w pad))

(defun area (w h)
  (let ((pad 2))
    (* (padded w pad) h)))" (after-edits text edits))))
  (let* ((text "(defun g (x) (foo (bar x) 1))")
         (start (search "(bar x)" text)))
    (is string= "(defun g (x) (let ((b (bar x)))
(foo b 1)))" (after-edits text (c:extract-variable-edits text start (+ start 7) "b"))))
  (fail (c:extract-function-edits "(a b)" 0 0 "f")))

(define-test regex-search :parent cadre-tests
  (is equal '((0 0 3) (1 4 7)) (c:text-matches (format nil "foo bar~%baz fox") "f.." :regex t))
  (is equal '((0 4 7)) (c:text-matches "Foo foo" "f\\w+" :regex t :case-sensitive t))
  (is equal '((0 0 3) (0 4 7)) (c:text-matches "Foo foo" "f\\w+" :regex t))
  (is equal '((0 6 9)) (c:text-matches "foo-x foo" "fo+" :regex t :whole-word t))
  (fail (c:text-matches "x" "(" :regex t))
  (is string= "b-a" (c:regex-replacement "(a)-(b)" "a-b" "\\2-\\1")))

(define-test source-definitions :parent cadre-tests
  (let ((defs (c:source-definitions "(in-package :foo)
(defun add-two (a b &optional (c 3))
  \"Add things.
Over lines.\"
  (+ a b c))
(defvar *x* 10 \"the x\")
(eval-when (:compile-toplevel)
  (defmacro with-thing ((var thing)
                        &body body)
    `(let ((,var ,thing)) ,@body)))
(defmethod frob :around ((x integer) &key verbose) (call-next-method))
(defstruct (point (:conc-name p-)) \"A point.\" x y)
(defgeneric area (shape) (:documentation \"The area.\"))
(defun lone () \"just a string\")")))
    (is equal '("add-two" "*x*" "with-thing" "frob" "point" "area" "lone") (mapcar #'c:definition-name defs))
    (is equal '(:function :variable :macro :method :class :generic :function) (mapcar #'c:definition-kind defs))
    (is equal '("(a b &optional (c 3))" nil "((var thing) &body body)" "((x integer) &key verbose)" nil "(shape)" "()")
        (mapcar #'c:definition-arglist defs))
    (is equal (list (format nil "Add things.~%Over lines.") "the x" nil nil "A point." "The area." nil)
        (mapcar #'c:definition-documentation defs))
    (is = 1 (c:definition-line (first defs)))))

(define-test arglist-hints :parent cadre-tests
  (is string= "(f a ===> b <=== &optional c)" (c:arglist-hint "f" "(a b &optional c)" 1))
  (is string= "(f a b &optional ===> c <===)" (c:arglist-hint "f" "(a b &optional c)" 2))
  (is string= "(f a b &optional c)" (c:arglist-hint "f" "(a b &optional c)" 3))
  (is string= "(f a &rest ===> more <===)" (c:arglist-hint "f" "(a &rest more)" 4))
  (is string= "(f a &key ===> (size 1) <=== color)" (c:arglist-hint "f" "(a &key (size 1) color)" 2 ":size"))
  (is string= "(f a &key size color)" (c:arglist-hint "f" "(a &key size color)" 1))
  (is string= "(f)" (c:arglist-hint "f" "()" 0))
  (is string= "(f a b)" (c:arglist-hint "f" "(a
   b)"))
  (let ((m c:+cursor-marker+))
    (is equal '(("f" 1 nil)) (c:form-argument-position (list "f" "1" "" m) m))
    (is equal '(("g" 0 nil) ("x" 0 nil) ("let" 0 nil))
        (c:form-argument-position (list "let" (list (list "x" (list "g" "q" m)))) m))
    (is equal '(("f" 2 ":key")) (c:form-argument-position (list "f" "a" ":key" "v" m) m))))

(define-test standard-symbols :parent cadre-tests
  (is string= "(function list &rest more-lists)" (c:standard-arglist "mapcar"))
  (is string= "(function list &rest more-lists)" (c:standard-arglist "CL:MAPCAR"))
  (is eq nil (c:standard-arglist "no-such-function"))
  (is eq :macro (c:standard-symbol-kind (c:standard-symbol "defun")))
  (is eq :special (c:standard-symbol-kind (c:standard-symbol "let")))
  (true (find "with-open-file" (c:standard-symbols) :key #'car :test #'string=)))
