(in-package #:cadre-tests)

;;; Paredit. Texts mark the cursor with |.

(defun text-with-cursor (string)
  (let* ((point (position #\| string))
         (text (c:make-string-text (remove #\| string :count 1))))
    (setf (c:text-point text) point)
    text))

(defun shown-with-cursor (text)
  (let ((s (c:text-string text)) (p (c:text-point text)))
    (concatenate 'string (subseq s 0 p) "|" (subseq s p))))

(defun paredit (function string &rest args)
  "STRING after FUNCTION, with the cursor shown as |."
  (let* ((text (text-with-cursor string))
         (syntax (c:make-lisp-syntax text)))
    (multiple-value-bind (line column) (c:text-position-line text (c:text-point text))
      (multiple-value-bind (edits point stick delta) (apply function syntax line column args)
        (c:apply-edits text edits point (or stick :before) (or delta 0))
        (shown-with-cursor text)))))

(define-test paredit :parent cadre-tests
  (is string= "(a b| c)" (paredit #'c:paredit-slurp-forward "(a b|) c"))
  (is string= "(a (b| c d))" (paredit #'c:paredit-slurp-forward "(a (b| c) d)"))
  (is string= "(a b|) c" (paredit #'c:paredit-barf-forward "(a b| c)"))
  (is string= "(|)a" (paredit #'c:paredit-barf-forward "(|a)"))
  (is string= "(a b| c)" (paredit #'c:paredit-slurp-backward "a (b| c)"))
  (is string= "a (b| c)" (paredit #'c:paredit-barf-backward "(a b| c)"))
  (is string= "(let ((x 1)) |(foo x))" (paredit #'c:paredit-raise "(let ((x 1)) (when t |(foo x)))"))
  (is string= "(f |x)" (paredit #'c:paredit-raise "(f (g |x y))"))
  (is string= "(a b| c d)" (paredit #'c:paredit-splice "(a (b| c) d)"))
  (is string= "(a |c d)" (paredit #'c:paredit-splice-killing-backward "(a (b |c d))"))
  (is string= "(a b|)" (paredit #'c:paredit-splice-killing-forward "(a (b| c d))"))
  (is string= "((|(a b)) c)" (paredit #'c:paredit-wrap "(|(a b) c)"))
  (is string= "(f (|x))" (paredit #'c:paredit-wrap "(f |x)"))
  (is string= "(|)" (paredit #'c:paredit-wrap "|"))
  (is string= "(a b)| (c)" (paredit #'c:paredit-split "(a b| c)"))
  (is string= "\"ab\"| \"cd\"" (paredit #'c:paredit-split "\"ab|cd\""))
  (is string= "(a b |c d)" (paredit #'c:paredit-join "(a b) |(c d)"))
  (fail (paredit #'c:paredit-slurp-forward "(a b|)"))
  (fail (paredit #'c:paredit-raise "|a"))
  ;; Typing
  (is string= "(f (|))" (paredit #'c:paredit-open "(f |)"))
  (is string= "\"(|\"" (paredit #'c:paredit-open "\"|\""))
  (is string= "#\\(|" (paredit #'c:paredit-open "#\\|"))
  (is string= "(a (b c)|)" (paredit #'c:paredit-close "(a (b c|  ))"))
  (is string= "(a (b c)|)" (paredit #'c:paredit-close "(a (b c|))"))
  (is string= "(f \"|\")" (paredit #'c:paredit-quote "(f |)"))
  (is string= "\"ab\"|" (paredit #'c:paredit-quote "\"ab|\""))
  (is string= "\"a\\\"|b\"" (paredit #'c:paredit-quote "\"a|b\""))
  ;; Deleting
  (is string= "(a (|))" (paredit #'c:paredit-delete-before "(a ()|)"))
  (is string= "(a |)" (paredit #'c:paredit-delete-before "(a (|))"))
  (is string= "(a (b)|)" (paredit #'c:paredit-delete-before "(a (b))|"))
  (is string= "(a |(b))" (paredit #'c:paredit-delete-before "(a (|b))"))
  (is string= "(a |)" (paredit #'c:paredit-delete-before "(a \"|\")"))
  (is string= "(a \"x|\")" (paredit #'c:paredit-delete-before "(a \"x\"|)"))
  (is string= "(ab|)" (paredit #'c:paredit-delete-before "(abc|)"))
  (is string= "(a |)" (paredit #'c:paredit-delete-after "(a |())"))
  (is string= "(a (|b))" (paredit #'c:paredit-delete-after "(a |(b))"))
  (is string= "(a b)|" (paredit #'c:paredit-delete-after "(a b|)"))
  (is string= "\"a|\"" (paredit #'c:paredit-delete-after "\"a|\\n\""))
  ;; How far C-k kills
  (flet ((kill-end (string)
           (let* ((text (text-with-cursor string))
                  (syntax (c:make-lisp-syntax text)))
             (multiple-value-bind (line column) (c:text-position-line text (c:text-point text))
               (let ((end (c:paredit-kill-end syntax line column)))
                 (concatenate 'string (c:text-string text 0 (c:text-point text)) (c:text-string text end)))))))
    (is string= "(a )" (kill-end "(a |b c)"))
    (is string= "(defun f ()
  
   (bar))" (kill-end "(defun f ()
  |(foo)
   (bar))"))
    (is string= "x ; c
y" (kill-end "x|(a
 b) ; c
y"))
    (is string= "(f \"ab\")" (kill-end "(f \"ab|cd\")"))
    (is string= "ab" (kill-end "a|
b"))))

;;; The kill ring

(define-test kill-ring :parent cadre-tests
  (let ((c:*kill-ring* '()) (c::*kill-ring-yank-index* 0) (c:*last-command-kind* nil) (c:*this-command-kind* nil))
    (fail (c:current-kill))
    (c:kill-text "one")
    (is string= "one" (c:current-kill))
    ;; A second kill right after joins the first.
    (setf c:*last-command-kind* :kill)
    (c:kill-text " two")
    (c:kill-text "zero " :direction :backward)
    (is equal '("zero one two") c:*kill-ring*)
    (setf c:*last-command-kind* nil)
    (c:kill-text "three")
    (c:kill-new "four")
    (is string= "four" (c:current-kill))
    (is string= "three" (c:current-kill 1))
    (is string= "zero one two" (c:current-kill 1))
    (is string= "four" (c:current-kill 1))
    (let ((c:*kill-ring-max* 2))
      (c:kill-new "five")
      (is = 2 (length c:*kill-ring*)))))

(define-test replacing :parent cadre-tests
  (is equal '((0 . 3) (8 . 11)) (c:find-all "foo" "Foo bar foo"))
  (is equal '((8 . 11)) (c:find-all "foo" "Foo bar foo" :case-fold nil))
  (is equal '((4 . 7)) (c:find-all "Bar" "foo Bar bar"))
  (is string= "bar" (c:replacement-for "foo" "bar"))
  (is string= "Bar" (c:replacement-for "Foo" "bar"))
  (is string= "BAR" (c:replacement-for "FOO" "bar"))
  (is string= "bAr" (c:replacement-for "FOO" "bAr"))
  (is equal '("Bar baz BAR" 2) (multiple-value-list (c:replace-all "foo" "bar" "Foo baz FOO")))
  (is string= "Hello" (c:capitalize-string "hELLO"))
  (is equal '("defun" "define-command") (c:dabbrev-candidates "def" "(defun x) (def| y) (define-command z) (defun w)" 14))
  (is equal '("make-buffer") (c:dabbrev-candidates "make-" "(make-buffer) make-" 19)))

(define-test minor-modes :parent cadre-tests
  (c:define-minor-mode test-minor-mode ())
  (let ((buffer (c:make-buffer :name "minor")))
    (unwind-protect
         (progn
           (false (c:minor-mode-enabled-p buffer 'test-minor-mode))
           (c:set-minor-mode buffer 'test-minor-mode t)
           (true (c:minor-mode-enabled-p buffer 'test-minor-mode))
           (is = 1 (length (c:buffer-minor-mode-keymaps buffer)))
           (c:set-minor-mode buffer 'test-minor-mode nil)
           (false (c:minor-mode-enabled-p buffer 'test-minor-mode)))
      (c:kill-buffer buffer))))

(define-test prefix-argument :parent cadre-tests
  (let ((count 0))
    (eval `(c:define-command test-repeated () (:repeat t) (incf ,(intern "*TEST-COUNT*" :cadre-tests))))
    (defparameter *test-count* 0)
    (let ((c:*prefix-arg* 3)) (c:run-command 'test-repeated))
    (is = 3 *test-count*)
    (let ((c:*prefix-arg* '(4))) (c:run-command 'test-repeated))
    (is = 7 *test-count*)
    (is = 1 (c:prefix-numeric-value nil))
    (setf count 0)
    count))

;;; Options, as the settings page edits them

(defvar *test-flag* nil)
(defvar *test-count* 3)
(defvar *test-choice* :a)
(defvar *test-name* nil)
(defvar *test-list* '("a"))

(define-test options :parent cadre-tests
  (c:define-option *test-flag* nil boolean "A flag." :category "Testing")
  (c:define-option *test-count* 3 (integer 1 10) "A count.")
  (c:define-option *test-choice* :a (member :a :b) "A choice.")
  (c:define-option *test-name* nil (or null string) "A name.")
  (c:define-option *test-list* '("a") list "A list.")
  (flet ((o (name) (c:find-option name)))
    (is string= "Testing" (c:option-category (o '*test-flag*)))
    (is string= "Other" (c:option-category (o '*test-count*)))
    (is string= "Test count" (c:option-title (o '*test-count*)))
    (is eq :boolean (c:option-kind (o '*test-flag*)))
    (is equal '(:integer 1 10) (c:option-kind (o '*test-count*)))
    (is equal '(:choice (:a :b)) (c:option-kind (o '*test-choice*)))
    (is eq :optional-string (c:option-kind (o '*test-name*)))
    (is eq :lisp (c:option-kind (o '*test-list*)))
    (is equal '("x" "y") (c:read-option-value (o '*test-list*) "(\"x\" \"y\")"))
    (is eq nil (c:read-option-value (o '*test-name*) "  "))
    (is string= "Ann" (c:read-option-value (o '*test-name*) "Ann"))
    (is = 7 (c:read-option-value (o '*test-count*) "7"))
    (fail (c:read-option-value (o '*test-count*) "70"))
    (fail (c:read-option-value (o '*test-list*) "(oops"))
    (fail (c:read-option-value (o '*test-list*) "#.(error \"no\")"))
    (fail (c:set-option-value (o '*test-choice*) :c))
    (c:set-option-value (o '*test-choice*) :b)
    (is eq :b *test-choice*)
    (is string= "(\"a\")" (c:write-option-value (o '*test-list*)))
    (is string= "" (c:write-option-value (o '*test-name*)))))

;;; Searching and refactoring

(define-test project-search :parent cadre-tests
  (is equal '((0 4 7) (1 0 3)) (c:text-matches (format nil "the foo~%Foo-bar") "foo"))
  (is equal '((0 4 7)) (c:text-matches (format nil "the foo~%Foo-bar") "foo" :whole-word t))
  (is equal '((1 0 3)) (c:text-matches (format nil "the foo~%Foo-bar") "Foo" :case-sensitive t))
  (is equal '((0 7 10) (1 10 13))
      (c:symbol-occurrences (format nil "(defun foo () \"foo\") ; foo~%(cl-user::foo 1 foo-bar)") "foo"))
  (is equal '((0 1 4)) (c:symbol-occurrences "(Bar)" "pkg:bar"))
  (is string= (format nil "(defun baz () \"foo\")~%(baz)")
      (c:replace-matches (format nil "(defun foo () \"foo\")~%(foo)")
                         (c:symbol-occurrences (format nil "(defun foo () \"foo\")~%(foo)") "foo") "baz")))

(defun after-edits (text edits)
  (let ((st (c:make-string-text text)))
    (c:apply-edits st edits 0)
    (c:text-string st)))

(define-test refactoring :parent cadre-tests
  (let ((tree (c:read-form-tree "(a (b c) ; x
 \"s\")")))
    (is = 1 (length tree))
    (is = 3 (length (fourth (first tree)))))
  (let ((text "(defun f (x &key (y 2)) (let ((z 3)) (+ x y z w)))"))
    (let ((start (search "(+ x" text)))
      (is equal '("x" "y" "z") (sort (c:bound-variables-at (c:read-form-tree text) start (+ start 11)) #'string<))))
  (let* ((text "(defun area (w h)
  (let ((pad 2))
    (* (+ w pad) h)))")
         (start (search "(+ w pad)" text)))
    (multiple-value-bind (edits params) (c:extract-function-edits text start (+ start 9) "padded")
      (is equal '("w" "pad") params)
      (is string= "(defun padded (w pad)
  (+ w pad))

(defun area (w h)
  (let ((pad 2))
    (* (padded w pad) h)))" (after-edits text edits))))
  (let* ((text "(defun g (x) (foo (bar x) 1))")
         (start (search "(bar x)" text)))
    (is string= "(defun g (x) (let ((b (bar x)))
(foo b 1)))" (after-edits text (c:extract-variable-edits text start (+ start 7) "b"))))
  (fail (c:extract-function-edits "(a b)" 0 0 "f")))

(define-test regex-search :parent cadre-tests
  (is equal '((0 0 3) (1 4 7)) (c:text-matches (format nil "foo bar~%baz fox") "f.." :regex t))
  (is equal '((0 4 7)) (c:text-matches "Foo foo" "f\\w+" :regex t :case-sensitive t))
  (is equal '((0 0 3) (0 4 7)) (c:text-matches "Foo foo" "f\\w+" :regex t))
  (is equal '((0 6 9)) (c:text-matches "foo-x foo" "fo+" :regex t :whole-word t))
  (fail (c:text-matches "x" "(" :regex t))
  (is string= "b-a" (c:regex-replacement "(a)-(b)" "a-b" "\\2-\\1")))

(define-test source-definitions :parent cadre-tests
  (let ((defs (c:source-definitions "(in-package :foo)
(defun add-two (a b &optional (c 3))
  \"Add things.
Over lines.\"
  (+ a b c))
(defvar *x* 10 \"the x\")
(eval-when (:compile-toplevel)
  (defmacro with-thing ((var thing)
                        &body body)
    `(let ((,var ,thing)) ,@body)))
(defmethod frob :around ((x integer) &key verbose) (call-next-method))
(defstruct (point (:conc-name p-)) \"A point.\" x y)
(defgeneric area (shape) (:documentation \"The area.\"))
(defun lone () \"just a string\")")))
    (is equal '("add-two" "*x*" "with-thing" "frob" "point" "area" "lone") (mapcar #'c:definition-name defs))
    (is equal '(:function :variable :macro :method :class :generic :function) (mapcar #'c:definition-kind defs))
    (is equal '("(a b &optional (c 3))" nil "((var thing) &body body)" "((x integer) &key verbose)" nil "(shape)" "()")
        (mapcar #'c:definition-arglist defs))
    (is equal (list (format nil "Add things.~%Over lines.") "the x" nil nil "A point." "The area." nil)
        (mapcar #'c:definition-documentation defs))
    (is = 1 (c:definition-line (first defs)))))

(define-test arglist-hints :parent cadre-tests
  (is string= "(f a ===> b <=== &optional c)" (c:arglist-hint "f" "(a b &optional c)" 1))
  (is string= "(f a b &optional ===> c <===)" (c:arglist-hint "f" "(a b &optional c)" 2))
  (is string= "(f a b &optional c)" (c:arglist-hint "f" "(a b &optional c)" 3))
  (is string= "(f a &rest ===> more <===)" (c:arglist-hint "f" "(a &rest more)" 4))
  (is string= "(f a &key ===> (size 1) <=== color)" (c:arglist-hint "f" "(a &key (size 1) color)" 2 ":size"))
  (is string= "(f a &key size color)" (c:arglist-hint "f" "(a &key size color)" 1))
  (is string= "(f)" (c:arglist-hint "f" "()" 0))
  (is string= "(f a b)" (c:arglist-hint "f" "(a
   b)"))
  (let ((m c:+cursor-marker+))
    (is equal '(("f" 1 nil)) (c:form-argument-position (list "f" "1" "" m) m))
    (is equal '(("g" 0 nil) ("x" 0 nil) ("let" 0 nil))
        (c:form-argument-position (list "let" (list (list "x" (list "g" "q" m)))) m))
    (is equal '(("f" 2 ":key")) (c:form-argument-position (list "f" "a" ":key" "v" m) m))))

(define-test standard-symbols :parent cadre-tests
  (is string= "(function list &rest more-lists)" (c:standard-arglist "mapcar"))
  (is string= "(function list &rest more-lists)" (c:standard-arglist "CL:MAPCAR"))
  (is eq nil (c:standard-arglist "no-such-function"))
  (is eq :macro (c:standard-symbol-kind (c:standard-symbol "defun")))
  (is eq :special (c:standard-symbol-kind (c:standard-symbol "let")))
  (true (find "with-open-file" (c:standard-symbols) :key #'car :test #'string=)))

;;; Markdown

(defun md-faces (line &optional (state '(:text)))
  (mapcar (lambda (s) (list (third s) (subseq line (first s) (second s))))
          (c:markdown-line-spans line state)))

(define-test markdown-highlighting :parent cadre-tests
  (is equal '((:md-markup "# ") (:md-heading "# Title")) (md-faces "# Title"))
  (let ((faces (md-faces "a **b** _c_ `d` [e](f)")))
    (true (member '(:md-strong "**b**") faces :test #'equal))
    (true (member '(:md-emphasis "_c_") faces :test #'equal))
    (true (member '(:md-code "d") faces :test #'equal))
    (true (member '(:md-link "e") faces :test #'equal))
    (true (member '(:md-url "f") faces :test #'equal)))
  (is equal nil (md-faces "snake_case_name and 2 * 3 * 4"))
  (is equal '((:md-markup "\\") (:md-markup "\\")) (md-faces "\\*not emphasis\\*"))
  (is equal '((:md-list "-") (:md-list "[x]")) (md-faces "- [x] done"))
  (is equal '((:md-list "12.")) (md-faces "12. twelve"))
  (multiple-value-bind (spans state) (c:markdown-line-spans "```lisp" '(:text))
    (declare (ignore spans))
    (is equal '(:fence #\` 3 (:code 0)) state)
    (let ((faces (md-faces "(defun f ())" state)))
      (true (member '(:definer "defun") faces :test #'equal))
      (true (member '(:md-code-block "(defun f ())") faces :test #'equal)))
    (is equal '(:text) (nth-value 1 (c:markdown-line-spans "```" state))))
  (is equal '(:fence #\~ 4 nil) (nth-value 1 (c:markdown-line-spans "~~~~ text" '(:text)))))

(define-test markdown-blocks :parent cadre-tests
  (let ((blocks (c:markdown-blocks (format nil "Title~%=====~%~%One~%two  ~%three~%~%- a~%- [ ] b~%  - c~%~%3. x~%~%> q~%~%```lisp~%(+ 1 2)~%```~%~%| h | i |~%|:-|-:|~%| 1 | 2 |~%~%***~%~%    code"))))
    (is equal '(:heading :paragraph :list :list :quote :code :table :rule :code) (mapcar #'first blocks))
    (is equal "Title" (car (third (first blocks))))
    (is equal (format nil "One two~%three") (car (second (second blocks))))
    (let ((items (fourth (third blocks))))
      (is = 2 (length items))
      (is eq :open (first (second items)))
      (is equal '(:paragraph :list) (mapcar #'first (second (second items)))))
    (is eq t (second (fourth blocks)))
    (is = 3 (third (fourth blocks)))
    (is equal '("lisp" "(+ 1 2)") (subseq (sixth blocks) 1 3))
    (is equal '(:left :right) (second (seventh blocks)))
    (is equal "code" (third (ninth blocks)))
    (is = 0 (car (last (first blocks))))
    (is = 3 (car (last (second blocks))))))

(define-test markdown-misc :parent cadre-tests
  (is equal '((1 "A" 0) (2 "B c" 2) (1 "D" 4))
      (c:markdown-headings (format nil "# A~%~%## B *c*~%~%D~%==~%```~%# not~%```")))
  (is equal '("- " nil) (multiple-value-list (c:markdown-continuation "- item")))
  (is equal '("  4) " nil) (multiple-value-list (c:markdown-continuation "  3) x")))
  (is equal '("- " t) (multiple-value-list (c:markdown-continuation "- ")))
  (is equal '("> - [ ] " nil) (multiple-value-list (c:markdown-continuation "> - [x] a")))
  (is equal '(nil nil) (multiple-value-list (c:markdown-continuation "plain")))
  (let ((link (find :link (c:markdown-inlines "see [the docs](https://x.org/a_b) now") :key #'first)))
    (is equal "https://x.org/a_b" (ninth link)))
  (is equal "a b" (c:inline-plain-text (cons "*a* `b`" (c:markdown-inlines "*a* `b`")))))

;;; Git

(define-test git-parsing :parent cadre-tests
  (is equal '(10 2 10 3) (c::parse-hunk-header "@@ -10,2 +10,3 @@ (defun f ()"))
  (is equal '(5 0 6 2) (c::parse-hunk-header "@@ -5,0 +6,2 @@"))
  (is equal '(7 1 7 1) (c::parse-hunk-header "@@ -7 +7 @@"))
  (is equal '((#\M #\Space "src/a.lisp" nil) (#\? #\? "new file.md" nil) (#\R #\Space "b.lisp" "old.lisp"))
      (c:parse-git-status (format nil "M  src/a.lisp~a?? new file.md~aR  b.lisp~aold.lisp~a"
                                  (code-char 0) (code-char 0) (code-char 0) (code-char 0))))
  (is eq :untracked (c:git-status-kind #\? #\?))
  (is eq :modified (c:git-status-kind #\Space #\M))
  (is eq :added (c:git-status-kind #\A #\Space))
  (is eq :conflict (c:git-status-kind #\U #\U)))

(define-test git-changes :parent cadre-tests
  (when (c:git-available-p)
    (let ((old (format nil "a~%b~%c~%d~%"))
          (new (format nil "a~%B~%c~%d~%e~%")))
      (is equal '((2 1 2 1) (4 0 5 1)) (c:line-changes old new))
      (is equal '(:modified :added) (mapcar #'c:hunk-kind (c:line-changes old new)))
      (is equal '((2 1 1 0)) (c:line-changes old (format nil "a~%c~%d~%")))
      (is equal '() (c:line-changes old old)))
    ;; A repository: status, HEAD text, staging, committing.
    (let ((root (uiop:ensure-directory-pathname
                 (merge-pathnames (format nil "cadre-git-test-~d/" (random 1000000)) (uiop:temporary-directory)))))
      (ensure-directories-exist root)
      (unwind-protect
           (progn
             (c:git-ok root "init" "-q")
             (c:git-ok root "config" "user.email" "test@example.com")
             (c:git-ok root "config" "user.name" "Test")
             (with-open-file (o (merge-pathnames "a.lisp" root) :direction :output) (format o "(one)~%"))
             (is equal '((#\? #\? "a.lisp" nil)) (c:git-status root))
             (c:git-stage root '("a.lisp"))
             (is equal '((#\A #\Space "a.lisp" nil)) (c:git-status root))
             (c:git-unstage root '("a.lisp"))
             (is equal '((#\? #\? "a.lisp" nil)) (c:git-status root))
             (c:git-stage root '("a.lisp"))
             (c:git-commit root "First")
             (is equal '() (c:git-status root))
             (is equal (format nil "(one)~%") (c:git-head-text root "a.lisp"))
             (true (c:git-branch root))
             (is equal (namestring (truename root)) (namestring (c:git-toplevel (merge-pathnames "a.lisp" root))))
             (with-open-file (o (merge-pathnames "a.lisp" root) :direction :output :if-exists :supersede) (format o "(two)~%"))
             (is equal '((#\Space #\M "a.lisp" nil)) (c:git-status root))
             (true (search "+(two)" (c:git-diff-text root "a.lisp")))
             (c:git-discard root '("a.lisp"))
             (is equal '() (c:git-status root))
             (fail (c:git-ok root "frobnicate") 'c:editor-error))
        (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore)))))

(define-test git-branches-and-remotes :parent cadre-tests
  (when (c:git-available-p)
    (let* ((base (uiop:ensure-directory-pathname
                  (merge-pathnames (format nil "cadre-git-remote-~d/" (random 1000000)) (uiop:temporary-directory))))
           (remote (merge-pathnames "remote.git/" base))
           (work (merge-pathnames "work/" base))
           (other (merge-pathnames "other/" base)))
      (ensure-directories-exist remote)
      (ensure-directories-exist work)
      (unwind-protect
           (flet ((setup (dir)
                    (c:git-ok dir "config" "user.email" "test@example.com")
                    (c:git-ok dir "config" "user.name" "Test"))
                  (write-file (dir name text)
                    (with-open-file (o (merge-pathnames name dir) :direction :output :if-exists :supersede)
                      (write-string text o))))
             (c:git-ok remote "init" "-q" "--bare" "-b" "main")
             (c:git-ok work "init" "-q" "-b" "main")
             (setup work)
             (write-file work "a.txt" "one")
             (c:git-stage work '("a.txt"))
             (c:git-commit work "First")
             (c:git-ok work "remote" "add" "origin" (uiop:native-namestring remote))
             (is equal '("origin") (c:git-remotes work))
             (is eq nil (c:git-upstream work))
             (c:git-push work :set-upstream "origin")
             (is equal "origin/main" (c:git-upstream work))
             (is equal '(0 0) (multiple-value-list (c:git-ahead-behind work)))
             (write-file work "a.txt" "two")
             (c:git-stage work '("a.txt"))
             (c:git-commit work "Second")
             (is equal '(1 0) (multiple-value-list (c:git-ahead-behind work)))
             (c:git-push work)
             (is equal '(0 0) (multiple-value-list (c:git-ahead-behind work)))
             ;; Another clone pushes; we fetch and pull.
             (c:git-ok base "clone" "-q" (uiop:native-namestring remote) "other")
             (setup other)
             (write-file other "b.txt" "bee")
             (c:git-stage other '("b.txt"))
             (c:git-commit other "Third")
             (c:git-push other)
             (c:git-fetch work)
             (is equal '(0 1) (multiple-value-list (c:git-ahead-behind work)))
             (c:git-pull work)
             (is equal '(0 0) (multiple-value-list (c:git-ahead-behind work)))
             (true (probe-file (merge-pathnames "b.txt" work)))
             ;; Branches
             (c:git-switch work "feature" :create t)
             (let ((branches (c:git-branches work)))
               (is equal "feature" (getf (find-if (lambda (b) (getf b :current)) branches) :name))
               (true (find "origin/main" branches :key (lambda (b) (getf b :name)) :test #'string=))
               (true (getf (find "origin/main" branches :key (lambda (b) (getf b :name)) :test #'string=) :remote)))
             (c:git-switch work "main")
             (c:git-delete-branch work "feature")
             (is eq nil (find "feature" (c:git-branches work) :key (lambda (b) (getf b :name)) :test #'string=))
             ;; A remote that isn't there fails rather than waiting.
             (c:git-ok work "remote" "add" "nowhere" "https://example.invalid/nothing.git")
             (fail (c:git-network work "fetch" "nowhere") 'c:editor-error))
        (uiop:delete-directory-tree base :validate t :if-does-not-exist :ignore)))))

(define-test git-history-blame-stash :parent cadre-tests
  (is string= "just now" (c:relative-time 1000 1030))
  (is string= "1 minute ago" (c:relative-time 1000 1070))
  (is string= "3 days ago" (c:relative-time 0 (* 3 86400)))
  (is string= "2 years ago" (c:relative-time 0 (* 2 366 86400)))
  (when (c:git-available-p)
    (let ((root (uiop:ensure-directory-pathname
                 (merge-pathnames (format nil "cadre-git-hist-~d/" (random 1000000)) (uiop:temporary-directory)))))
      (ensure-directories-exist root)
      (unwind-protect
           (flet ((write-file (text)
                    (with-open-file (o (merge-pathnames "a.txt" root) :direction :output :if-exists :supersede)
                      (write-string text o))))
             (c:git-ok root "init" "-q")
             (c:git-ok root "config" "user.email" "test@example.com")
             (c:git-ok root "config" "user.name" "Ada")
             (write-file (format nil "one~%two~%"))
             (c:git-stage root '("a.txt"))
             (c:git-commit root "First")
             (write-file (format nil "one~%TWO~%"))
             (c:git-stage root '("a.txt"))
             (c:git-commit root "Second")
             (let ((log (c:git-log root)))
               (is equal '("Second" "First") (mapcar (lambda (c) (getf c :subject)) log))
               (is string= "Ada" (getf (first log) :author))
               (true (< (abs (- (getf (first log) :time) (get-universal-time))) 120))
               (true (search "+TWO" (c:git-show-text root (getf (first log) :hash))))
               (is = 1 (length (c:git-log root :count 1)))
               (is equal '("First") (mapcar (lambda (c) (getf c :subject)) (c:git-log root :skip 1))))
             (is equal '("Second" "First") (mapcar (lambda (c) (getf c :subject)) (c:git-log root :path "a.txt")))
             ;; Blame, of the saved file and of edited text.
             (let ((blame (c:git-blame root "a.txt")))
               (is equal '("First" "Second") (map 'list (lambda (b) (getf b :summary)) blame))
               (is string= "Ada" (getf (aref blame 0) :author)))
             (let ((blame (c:git-blame root "a.txt" (format nil "one~%new~%TWO~%"))))
               (is = 3 (length blame))
               (true (getf (aref blame 1) :uncommitted))
               (false (getf (aref blame 2) :uncommitted)))
             ;; Stashes
             (write-file (format nil "one~%three~%"))
             (c:git-stash-push root :message "work in progress")
             (is equal '() (c:git-status root))
             (let ((stashes (c:git-stashes root)))
               (is = 1 (length stashes))
               (true (search "work in progress" (getf (first stashes) :subject)))
               (c:git-stash-apply root (getf (first stashes) :ref))
               (is = 1 (length (c:git-status root)))
               (is = 1 (length (c:git-stashes root)))
               (c:git-stash-drop root "stash@{0}")
               (is equal '() (c:git-stashes root))))
        (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore)))))

(define-test git-hunks-and-conflicts :parent cadre-tests
  (let ((conflicts (c:find-conflicts (format nil "a~%<<<<<<< HEAD~%ours~%=======~%theirs~%>>>>>>> other~%b~%<<<<<<< HEAD~%x~%||||||| base~%o~%=======~%y~%>>>>>>> other~%"))))
    (is equal '((:start 1 :base nil :middle 3 :end 5) (:start 7 :base 9 :middle 11 :end 13)) conflicts)
    (let ((lines (coerce (c:split-text-lines (format nil "a~%<<<<<<< HEAD~%ours~%=======~%theirs~%>>>>>>> other~%")) 'vector)))
      (is equal '("ours") (c:conflict-resolution lines (first conflicts) :ours))
      (is equal '("theirs") (c:conflict-resolution lines (first conflicts) :theirs))
      (is equal '("ours" "theirs") (c:conflict-resolution lines (first conflicts) :both))))
  (is equal '() (c:find-conflicts (format nil "no~%=======~%conflict~%")))
  (when (c:git-available-p)
    (let ((root (uiop:ensure-directory-pathname
                 (merge-pathnames (format nil "cadre-git-hunks-~d/" (random 1000000)) (uiop:temporary-directory)))))
      (ensure-directories-exist root)
      (unwind-protect
           (flet ((write-file (text)
                    (with-open-file (o (merge-pathnames "a.txt" root) :direction :output :if-exists :supersede)
                      (write-string text o)))
                  (staged () (c:git root "diff" "--cached" "--no-color" "-U0")))
             (c:git-ok root "init" "-q" "-b" "main")
             (c:git-ok root "config" "user.email" "test@example.com")
             (c:git-ok root "config" "user.name" "Test")
             (write-file (format nil "1~%2~%3~%4~%5~%6~%7~%8~%"))
             (c:git-stage root '("a.txt"))
             (c:git-commit root "First")
             ;; Two separate changes; stage only the second.
             (write-file (format nil "1~%TWO~%3~%4~%5~%6~%SEVEN~%8~%"))
             (is = 1 (c:git-stage-lines root "a.txt" 7 7))
             (true (search "+SEVEN" (staged)))
             (false (search "+TWO" (staged)))
             (is = 0 (c:git-stage-lines root "a.txt" 4 4))
             ;; Unstage it again with the cached diff's hunk, reversed.
             (let* ((diff (c:git root "diff" "--cached" "--no-color" "--" "a.txt"))
                    (hunk (first (c:diff-hunks diff))))
               (c:git-apply-patch root (c:hunk-patch (c:diff-file-header diff) hunk) :cached t :reverse t))
             (is string= "" (staged))
             ;; A merge with a conflict.
             (c:git-ok root "checkout" "-q" "-b" "other")
             (write-file (format nil "1~%OTHER~%3~%4~%5~%6~%7~%8~%"))
             (c:git-stage root '("a.txt"))
             (c:git-commit root "Other")
             (c:git-ok root "checkout" "-q" "main")
             (write-file (format nil "1~%MAIN~%3~%4~%5~%6~%7~%8~%"))
             (c:git-stage root '("a.txt"))
             (c:git-commit root "Main")
             (fail (c:git-merge root "other") 'c:editor-error)
             (is eq :merge (c:git-operation root))
             (true (search "Merge branch 'other'" (c:git-merge-message root)))
             (is eq :conflict (apply #'c:git-status-kind (subseq (first (c:git-status root)) 0 2)))
             (is = 1 (length (c:find-conflicts (uiop:read-file-string (merge-pathnames "a.txt" root)))))
             (write-file (format nil "1~%MAIN~%OTHER~%3~%4~%5~%6~%7~%8~%"))
             (c:git-stage root '("a.txt"))
             (c:git-continue root :merge)
             (is eq nil (c:git-operation root))
             (true (search "Merge branch 'other'" (c:git-ok root "log" "-1" "--format=%s"))))
        (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore)))))

(define-test project-files-through-links :parent cadre-tests
  ;; A project reached through a link (as /var is on macOS) still has its
  ;; subfolders walked; a link to a folder inside it is not followed.
  (let* ((base (merge-pathnames (format nil "cadre-links-~d/" (random 1000000)) (uiop:temporary-directory)))
         (real (merge-pathnames "real/" base))
         (via (merge-pathnames "via/" base)))
    (unwind-protect
         (progn
           (ensure-directories-exist (merge-pathnames "sub/a.lisp" real))
           (with-open-file (o (merge-pathnames "sub/a.lisp" real) :direction :output) (write-line "(a)" o))
           (sb-posix:symlink (string-right-trim "/" (namestring real)) (string-right-trim "/" (namestring via)))
           (sb-posix:symlink (string-right-trim "/" (namestring real)) (namestring (merge-pathnames "loop" real)))
           (true (c:directory-link-p via))
           (false (c:directory-link-p (merge-pathnames "sub/" real)))
           (is equal '("sub/a.lisp")
               (mapcar (lambda (f) (enough-namestring f via)) (c:project-files via))))
      (uiop:delete-directory-tree base :validate t :if-does-not-exist :ignore))))

(define-test new-project :parent cadre-tests
  (true (c:valid-project-name-p "my-app2"))
  (false (c:valid-project-name-p "My-App"))
  (false (c:valid-project-name-p "2app"))
  (false (c:valid-project-name-p "app-"))
  (false (c:valid-project-name-p ""))
  (is string= "a x b" (c:fill-template "a {{n}} b" '(:n "x")))
  (fail (c:project-files-for "Bad Name") 'c:editor-error)
  (let ((files (c:project-files-for "demo" :author "Pat" :description "A demo.")))
    (is equal '("demo.asd" "src/package.lisp" "src/main.lisp" "tests/main.lisp" "Makefile" "README.md" ".gitignore" "LICENSE")
        (mapcar #'car files))
    (true (search "Copyright (c)" (cdr (assoc "LICENSE" files :test #'string=))))
    (true (search (format nil "~%test:~%~a$(RUN)" #\Tab) (cdr (assoc "Makefile" files :test #'string=))))
    (false (search "{{" (format nil "~{~a~}" (mapcar #'cdr files)))))
  (let ((files (c:project-files-for "tool" :kind :application :tests :fiveam :license nil)))
    (false (assoc "LICENSE" files :test #'string=))
    (true (search ":entry-point \"tool:main\"" (cdr (assoc "tool.asd" files :test #'string=))))
    (true (search "def-suite tool" (cdr (assoc "tests/main.lisp" files :test #'string=))))
    (true (search "build:" (cdr (assoc "Makefile" files :test #'string=))))
    ;; Every Lisp file reads (given the package the tests refer to).
    (unless (find-package "TOOL") (export (intern "HELLO" (make-package "TOOL" :use '())) "TOOL"))
    (dolist (path '("tool.asd" "src/package.lisp" "src/main.lisp" "tests/main.lisp"))
      (true (with-input-from-string (in (cdr (assoc path files :test #'string=)))
              (let ((*read-eval* nil) (*package* (make-package (gensym) :use '(:cl))))
                (loop for form = (read in nil :eof) until (eq form :eof) count t))))))
  ;; Made for real, the project loads and its own tests pass.
  (let ((parent (merge-pathnames (format nil "cadre-new-~d/" (random 1000000)) (uiop:temporary-directory))))
    (ensure-directories-exist parent)
    (unwind-protect
         (let ((dir (c:create-lisp-project parent "cadre-sample-proj" :author "Pat")))
           (true (probe-file (merge-pathnames "src/main.lisp" dir)))
           (fail (c:create-lisp-project parent "cadre-sample-proj") 'c:editor-error)
           (asdf:load-asd (merge-pathnames "cadre-sample-proj.asd" dir))
           (asdf:load-system "cadre-sample-proj/tests")
           (is eq :passed (parachute:status (parachute:test (find-symbol "CADRE-SAMPLE-PROJ" "CADRE-SAMPLE-PROJ/TESTS")
                                                            :report 'parachute:quiet))))
      (asdf:clear-system "cadre-sample-proj")
      (asdf:clear-system "cadre-sample-proj/tests")
      (uiop:delete-directory-tree parent :validate t :if-does-not-exist :ignore)))
  (when (find-package "TOOL") (delete-package "TOOL")))

(define-test build-plan :parent cadre-tests
  (let ((parent (merge-pathnames (format nil "cadre-build-~d/" (random 1000000)) (uiop:temporary-directory))))
    (ensure-directories-exist parent)
    (unwind-protect
         (let ((app (c:create-lisp-project parent "app" :kind :application))
               (lib (c:create-lisp-project parent "lib")))
           ;; A new application builds with its Makefile, a library doesn't build.
           (let ((plan (c:project-build-plan app)))
             (is string= "make" (getf plan :program))
             (is equal '("build") (getf plan :arguments))
             (true (search "bin/app" (getf plan :output))))
           (is eq nil (c:project-build-plan lib))
           ;; Run App: an application's entry point; a library has none.
           (is equal '(:system "app" :entry "app:main" :gtk nil :raylib nil) (c:project-app app))
           (is eq nil (c:project-app lib))
           (is equal '("test") (getf (c:project-test-plan lib "lib") :arguments))
           (false (c:makefile-has-target-p (merge-pathnames "Makefile" lib) "build"))
           (true (c:makefile-has-target-p (merge-pathnames "Makefile" lib) "test"))
           ;; Without the Makefile, ASDF's make in a new Lisp.
           (delete-file (merge-pathnames "Makefile" app))
           (let ((plan (c:project-build-plan app :lisp "sbcl")))
             (is string= "sbcl" (getf plan :program))
             (true (find "(asdf:make \"app\")" (getf plan :arguments) :test #'string=))
             (true (find "(asdf:test-system \"app\")" (getf (c:project-test-plan app "app" :lisp "sbcl") :arguments) :test #'string=))
             (is string= "bin/app" (c:asd-build-pathname (merge-pathnames "app.asd" app)))))
      (uiop:delete-directory-tree parent :validate t :if-does-not-exist :ignore))))

(define-test new-gtk-project :parent cadre-tests
  (let ((files (c:project-files-for "my-gui" :kind :gtk-application)))
    (let ((asd (cdr (assoc "my-gui.asd" files :test #'string=)))
          (main (cdr (assoc "src/main.lisp" files :test #'string=)))
          (makefile (cdr (assoc "Makefile" files :test #'string=))))
      (true (search ":depends-on (\"gtk4\")" asd))
      (true (search ":entry-point \"my-gui:main\"" asd))
      (is string= "my-gui:main" (c:asd-entry-point asd))
      (true (c:asd-uses-gtk4-p asd))
      (false (search ":build-operation" asd))
      (true (search "org.example.my_gui" main))
      (true (search "gio:application-run" main))
      (true (search "gtk4:save-executable" makefile))
      (true (search (format nil "~%dev:~%") makefile))
      (true (search "Run GTK App" (cdr (assoc "README.md" files :test #'string=))))))
  (true (c:asd-uses-gtk4-p "(defsystem \"x\" :depends-on (:alexandria #:gtk4))"))
  (false (c:asd-uses-gtk4-p "(defsystem \"x\" :depends-on (\"gtk4-extras\" \"alexandria\"))"))
  (false (c:asd-uses-gtk4-p "(defsystem \"x\" :depends-on ())"))
  (true (c:asd-depends-on-p "(defsystem \"game\" :depends-on (:raylib))" "raylib"))
  (false (c:asd-depends-on-p "(defsystem \"x\" :depends-on (\"raylib-generator\"))" "raylib"))
  ;; Pictures open to be looked at; SVG is text, and stays editable.
  (true (c:image-file-p #p"assets/knight_f0.png"))
  (true (c:image-file-p #p"photo.JPG"))
  (false (c:image-file-p #p"icon.svg"))
  (false (c:image-file-p #p"main.lisp"))
  ;; Plain projects have no dependencies.
  (true (search ":depends-on ()" (cdr (assoc "lib.asd" (c:project-files-for "lib") :test #'string=)))))

(define-test format-json :parent cadre-tests
  (is string= (format nil "{~%  \"a\": 1,~%  \"b\": [~%    true,~%    null~%  ],~%  \"c\": {},~%  \"d\": []~%}~%")
      (c:format-json "{\"a\":1,\"b\":[true,null],\"c\":{ },\"d\":[]}"))
  ;; Strings keep their contents (braces, escapes), numbers their spelling.
  (is string= (format nil "{~%  \"s\": \"{a, b: \\\"c\\\"}\",~%  \"n\": 1.50e3~%}~%")
      (c:format-json "{ \"s\" : \"{a, b: \\\"c\\\"}\" , \"n\" : 1.50e3 }"))
  ;; Already formatted stays the same; four-space indentation on request.
  (let ((once (c:format-json "[1,[2,3]]")))
    (is string= once (c:format-json once)))
  (is string= (format nil "[~%    1~%]~%") (c:format-json "[1]" :indent 4))
  ;; JSONC comments are kept.
  (is string= (format nil "{~%  // the name~%  \"a\": 1, // one~%  \"b\": 2~%}~%")
      (c:format-json (format nil "{ // the name~%\"a\": 1, // one~%\"b\": 2}"))))

(define-test format-xml :parent cadre-tests
  (is string= (format nil "<?xml version=\"1.0\"?>~%<a x=\"1>2\">~%  <b>text</b>~%  <c/>~%  <d></d>~%  <e>~%    <!-- note -->~%    <f>1</f>~%  </e>~%</a>~%")
      (c:format-xml "<?xml version=\"1.0\"?><a x=\"1>2\"><b> text </b><c/><d></d><e><!-- note --><f>1</f></e></a>"))
  ;; CDATA and the doctype come out as they went in; laid out stays the same.
  (let ((text (format nil "<!DOCTYPE note [<!ELEMENT note (#PCDATA)>]>~%<note>~%  <![CDATA[<raw> & ]]>~%</note>~%")))
    (is string= text (c:format-xml text))
    (is string= text (c:format-xml (remove #\Newline text))))
  (is string= (format nil "<a>~%  one~%  <b/>~%  two~%</a>~%") (c:format-xml "<a>one<b/>two</a>")
      "mixed content: text on its own lines")
  (is string= (format nil "<a>~%    <b/>~%</a>~%") (c:format-xml "<a><b/></a>" :indent 4)))

(define-test mode-for-text :parent cadre-tests
  (is eq 'c:xml-mode (c:major-mode-for-text (format nil "  ~%<?xml version=\"1.0\"?><a/>")))
  (is eq 'c:xml-mode (c:major-mode-for-text "<root><x/></root>"))
  (is eq 'c:html-mode (c:major-mode-for-text "<!DOCTYPE html><html></html>"))
  (is eq 'c:json-mode (c:major-mode-for-text "{\"a\": 1}"))
  (is eq 'c:lisp-mode (c:major-mode-for-text "(a b)"))
  (is eq 'c:fundamental-mode (c:major-mode-for-text "a < b"))
  (is eq 'c:fundamental-mode (c:major-mode-for-text "")))

(define-test format-css :parent cadre-tests
  (is string= (format nil "a, b > c {~%  color: red;~%  margin: 0 auto;~%}~%~%p {~%  font: 12px \"A  B\";~%}~%")
      (c:format-css "a,b > c{color:red;margin:0   auto}p{font:12px \"A  B\"}"))
  ;; Nested rules, at-rules, comments, and URLs with semicolons stay whole.
  (is string= (format nil "@import url(\"x;y.css\");~%~%@media (max-width: 600px) {~%  p:hover {~%    color: blue;~%  }~%}~%~%/* end */~%")
      (c:format-css "@import url(\"x;y.css\");@media (max-width: 600px){p:hover{color:blue;}}/* end */"))
  (let ((once (c:format-css "a{b:c}")))
    (is string= once (c:format-css once))))
