(in-package #:cadre-tests)

(define-test canonical-keys :parent cadre-tests
  (is string= "C-x" (c:canonical-key "C-x"))
  (is string= "C-S-p" (c:canonical-key "C-P"))
  (is string= "C-S-p" (c:canonical-key "S-C-p"))
  (is string= "C-M-s-S-a" (c:canonical-key "S-s-M-C-a"))
  (is string= "M-<" (c:canonical-key "M-<"))
  (is string= "C-?" (c:canonical-key "C-S-?"))
  (is string= "RET" (c:canonical-key "<return>"))
  (is string= "C-SPC" (c:canonical-key "C-space"))
  (is string= "C--" (c:canonical-key "C--"))
  (is string= "C-Page_Down" (c:canonical-key "C-Page_Down"))
  (is string= "C-S-TAB" (c:make-key "Tab" :control t :shift t))
  (is equal '("C-x" "C-f") (c:parse-keys "C-x  C-f"))
  (is string= "C-x C-f" (c:keys-string (c:parse-keys "C-x C-f"))))

(define-test keymap-lookup :parent cadre-tests
  (let ((global (c:make-keymap :global))
        (mode (c:make-keymap :mode)))
    (c:bind-key global "C-x C-f" 'open)
    (c:bind-key global "C-x C-s" 'save)
    (c:bind-key global "C-s" 'search)
    (c:bind-key mode "C-c C-c" 'compile)
    (c:bind-key mode "C-s" 'lisp-search)
    (is eq 'open (c:keymap-lookup global (c:parse-keys "C-x C-f")))
    (of-type c:keymap (c:keymap-lookup global (c:parse-keys "C-x")))
    (false (c:keymap-lookup global (c:parse-keys "C-x C-q")))
    (false (c:keymap-lookup global (c:parse-keys "C-s C-s")))
    (is eq 'lisp-search (c:lookup-keys (list mode global) (c:parse-keys "C-s")))
    (is eq 'save (c:lookup-keys (list mode global) (c:parse-keys "C-x C-s")))
    (is equal '("C-x C-f") (c:where-is 'open (list mode global)))
    (c:unbind-key global "C-x C-f")
    (false (c:keymap-lookup global (c:parse-keys "C-x C-f")))
    (let ((child (c:make-keymap :child global)))
      (is eq 'save (c:keymap-lookup child (c:parse-keys "C-x C-s"))))))

(define-test key-dispatch :parent cadre-tests
  (let ((map (c:make-keymap))
        (d (c:make-key-dispatcher)))
    (c:bind-key map "C-x C-f" 'open)
    (c:bind-key map "C-o" 'open)
    (is eq :prefix (c:dispatch-key d "C-x" (list map)))
    (is equal '("C-x") (c:dispatcher-pending d))
    (is equal '(:command ("C-x" "C-f") open)
        (multiple-value-list (c:dispatch-key d "C-f" (list map))))
    (is equal '() (c:dispatcher-pending d))
    (is eq :command (c:dispatch-key d "C-o" (list map)))
    (is eq :unbound (c:dispatch-key d "a" (list map)))
    (c:dispatch-key d "C-x" (list map))
    (is equal '(:undefined ("C-x" "C-q"))
        (multiple-value-list (c:dispatch-key d "C-q" (list map))))
    (is equal '() (c:dispatcher-pending d))))
